# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ovchipkaart

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io//
        username: ${{ secrets.AzureAppService_ContainerUsername_90f6570b5e7d4af285fce4566150321f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4376f96f62424888a0359dec16b1b6c8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/usigntech/ovchipkaart:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ovchipkaart'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e8b1b4a2d87141a890c3df13da39c899 }}
        images: 'ghcr.io//${{ secrets.AzureAppService_ContainerUsername_90f6570b5e7d4af285fce4566150321f }}/usigntech/ovchipkaart:${{ github.sha }}'